/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Blood": "血液",
    "Icons:": "图标:",
    ".. No Story ..": "..暂无剧情..",
    "A minimalist incremental game with a captivating backstory, offering rich layers of experience for you to explore on your adventure. I created this game out of my passion for the genre, inspired by titles like Armory & Machine, Antimatter Dimensions, A Dark Room, Universal Paperclips, and many others.\n": "这是一款极简的增量游戏，拥有迷人的背景故事，为你提供丰富的冒险体验。我是出于对这类游戏的热爱而创造了这款游戏，灵感来自于《军械库与机器》、《反物质维度》、《小黑屋》、《宇宙回形针》等游戏",
    "Bing Image Creator": "必应图像生成器",
    "Game data:\n": "游戏数据:\n",
    "Volume:\n": "音量:\n",
    "Credits:\n": "鸣谢:\n",
    "Game Time:": "游戏时长:",
    "Current Stage:": "当前阶段:",
    "Game Stats": "游戏统计",
    "Music:": "音乐:",
    "Images:": "图像:",
    "Icons:": "图标:",
    "Midnight Idle": "午夜放置",
    "Story": "剧情",
    "Skill": "技能",
    "Suck Blood": "吸血",
    "You awaken in an unfamiliar cave. A single thought consumes you—blood. The craving gnaws at your very core. Driven by instinct, you move with a slow, deliberate slither, your gelatinous form seeking sustenance. Spotting a nearby rat, fast asleep and unaware of the danger, you silently latch onto it, drawing its life’s blood to quench your hunger.": "你在一个陌生的洞穴中醒来。一个念头就会消耗你的血液。这种渴望啃噬着你的核心。在本能的驱使下，你缓慢而从容地滑行，你胶状的身体在寻找食物。发现附近一只熟睡的老鼠，没有意识到危险，你悄悄地抓住它，吸它的血来消除你的饥饿。",
    "If you’ve enjoyed the game and want to support its continued development—and future projects—please consider buying me a coffee. Your support makes all the difference!\n": "如果你喜欢这款游戏，并想支持它的继续发展——以及未来的项目——请考虑请我喝杯咖啡。你的支持让一切变得不同！\ n",
    "Midnight Idle v0.2.0 - by Wong Yat Seng": "午夜放置 v0.2.0 - 作者 Wong Yat Seng",
    "INTRODUCTION": "介绍",
    "Awareness": "意识",
    "Exported to clipboard.": "存档已导出并复制到剪贴板。",
    "MAX": "最大",
    "Anticoagulants": "抗凝血剂",
    "Appetite": "食欲",
    "Blood Sac": "血囊",
    "(Paused)": "(已暂停)",
    "(Auto)": "(自动)",
    "Freeflow": "自由流动",
    "Automated skills will activate and repeat automatically as long as their requirements are met. You can tap on the skill to start or pause any time.": "自动技能将被激活，并自动重复，只要他们的要求得到满足。您可以随时轻按开始或暂停该技能。",
    "AWARENESS": "意识",
    "Choose Bat": "选择蝙蝠",
    "Choose Wolf": "选择狼",
    "Trait": "特点",
    "You consume the rat completely, its essence merging with your own. As you do, a strange realization dawns—you’ve absorbed some of its abilities. Vision sharpens, scents fill the air, and faint sounds reach your awareness like never before. Empowered and emboldened, you begin to move about the cave, seeking your next target.": "你把老鼠完全吃掉，它的精华和你的精华融合在一起。当你这样做的时候，一个奇怪的意识出现了——你已经吸收了它的一些能力。视力变得敏锐，空气中充满了气味，微弱的声音前所未有地进入你的意识。你被赋予了力量和勇气，开始在洞穴里四处走动，寻找下一个目标。",
    "Potent Bite": "强咬力",
    "Echolocation": "回声定位",
    "Absorption": "吸收",
    "Neural Processing": "神经处理",
    "Signal Processing": "信号处理",
    "Agility": "敏捷",
    "BAT FORM": "蝙蝠形态",
    "As you absorb the bat pup, a wave of newfound abilities floods your senses. You gain a keen sense of echolocation, the ability to navigate in total darkness, and a faint awareness of air currents brushing against you. Your form begins to shift, taking on the rough outline of a bat, though your body still shimmers with dark, dripping ooze. With this enhanced mobility and perception, you take to exploring the cave, gliding through its shadowy depths with ease.": "当你吸收蝙蝠幼崽时，一波新发现的能力淹没了你的感官。你获得了敏锐的回声定位，在完全黑暗中导航的能力，以及对气流拂过你的微弱意识。你的形状开始改变，呈现出蝙蝠的轮廓，尽管你的身体仍然闪烁着黑色的、滴水的渗出物。有了这种增强的机动性和感知能力，你开始探索洞穴，轻松地在阴暗的深处滑行。",
    "Adventure": "冒险",
    "Exploration": "探索",
    "CALM POOL": "静水池",
    "Meditate": "冥想",
    "You discover a narrow path that leads to a serene chamber, where a calm pool of water rests undisturbed. The gentle stillness of the room beckons to you, offering a chance to recover from your weariness. Here, you can choose to meditate, allowing yourself a moment of reflection and restoration.": "你会发现一条狭窄的小路通向一个宁静的房间，那里有一池平静的水。房间里温柔的寂静在向你招手，给你一个从疲劳中恢复的机会。在这里，你可以选择冥想，让自己有片刻的反思和恢复。",
    "Restore Sanity": "恢复理智",
    "Sanity begins to take root within you, like a faint spark in the darkness. Fragmented thoughts and memories start to coalesce, offering glimpses of clarity amidst the primal hunger. As your sanity grows, so too will your ability to rise above your instinctual craving for blood. In time, you will gain the freedom to make your own choices, shaping your destiny beyond mere survival.": "理智开始在你心中扎根，就像黑暗中微弱的火花。支离破碎的思想和记忆开始融合在一起，在原始的饥饿中提供了清晰的一瞥。随着你理智的增长，你的能力也会超越你对血的本能渴望。随着时间的推移，你将获得做出自己选择的自由，塑造你的命运，而不仅仅是生存。",
    "SANITY": "理智",
    "Sanity": "理智",
    "Curiosity": "好奇心",
    "Greed": "贪婪",
    "Insight": "洞察力",
    "Clockwork": "发条装置",
    "Declutter": "清理器",
    "Expand Mind": "拓展思维",
    "Fast Thinking": "思维敏捷",
    "Quick Pacing": "快速节奏",
    "Sense of Direction": "辨识方向",
    "HEAVY TOME": "沉重的负担",
    "Devour Ancient Tome": "吞噬古籍",
    "Take Ancient Tome": "带上古籍",
    "You stumble upon a large, ancient tome resting on the floor, its once-pristine pages worn and faded by time. Though much of the writing is illegible, a sense of significance emanates from it. You can choose to pick it up and carry it with you, but be warned—its considerable weight will slow your pace, making exploration take longer.": "你偶然发现地板上放着一本古老的书籍，它曾经纯净的书页随着时间的流逝而磨损和褪色。虽然大部分文字难以辨认，但从中散发出一种意义。你可以选择拿起它并随身携带，但要注意的是，它相当重的重量会减慢你的步伐，使探索花费更长时间。",
    "Ancient Tome": "古籍",
    "LOCKED DOOR": "锁着的门",
    "You encounter a sturdy door, its surface adorned with an intricate puzzle lock that seems to guard the way forward. The choice is yours: you can carefully attempt to decipher the lock’s secrets, testing your wits and patience, or rely on sheer brute force to break the door down and force your way through.": "你遇到了一扇坚固的门，它的表面装饰着一个复杂的拼图锁，似乎守护着前进的道路。你的选择是：你可以小心翼翼地尝试破译锁的秘密，考验你的智慧和耐心，或者依靠纯粹的蛮力破门而入。",
    "Unlock Door": "打开门",
    "Break Down Door": "破门而入",
    "Fight Goblin": "对抗哥布林",
    "Goblin": "哥布林",
    "GOBLIN": "哥布林",
    "As you make your way down the passage, a menacing goblin emerges from the shadows, its eyes glinting with malice. This is no helpless prey like those you’ve encountered before—this creature is alert, hostile, and poses a genuine threat. You have no choice but to stand your ground and fight for your survival.": "当你沿着通道前进时，一个可怕的哥布林从阴影中出现，它的眼睛闪烁着恶意。这不是你以前遇到的那些无助的猎物——这种生物是警觉的，充满敌意的，并构成了真正的威胁。你别无选择，只能坚守阵地，为生存而战。",
    "Exp.": "经验值",
    "COMBAT": "战斗",
    "Heavy Slash": "重斩",
    "Escape": "逃跑",
    "Quick Slash": "快砍",
    "Defeat enemies by using a variety of combat attacks to reduce their HP to zero. Each attack is subject to an accuracy check to determine if it lands. The base critical hit rate is 5%. If the battle becomes too challenging, you can choose to escape at any time. Escaping from battle will cost you 2% of your XP, while being defeated will result in a 5% XP loss.": "使用各种战斗攻击将敌人的生命值降至零。每次攻击都要进行准确性检查，以确定攻击是否成功。基础暴击率为5%。如果战斗变得太有挑战性，你可以选择随时逃跑。逃离战斗将花费你2%的经验，而被打败将导致5%的经验损失。",
    "VICTORY": "胜利",
    "Absorb Goblin": "吸收哥布林",
    "NEW CLASS": "新种族",
    "Spare Goblin": "饶恕哥布林",
    "Defeated, the goblin collapses to the floor, barely clinging to life. As it struggles for breath, you are faced with a pivotal choice: absorb the goblin to gain its form and potential abilities, or reject the transformation and remain in your current feral, animalistic state. The decision is yours to make.": "小妖精被打败了，倒在地上，奄奄一息。当它挣扎着呼吸时，你面临着一个关键的选择：吸收地精以获得它的形态和潜在的能力，或者拒绝转变并保持你目前的野性，动物形态。决定权在你。",
    "FAMILIAR DUNGEON": "熟悉的地下城",
    "Shortcut": "捷径",
    "UNLIMITED": "无限",
    "With your new form, fragments of the goblin's memories flood your mind. These glimpses of its past grant you valuable insights into the cave dungeon, revealing hidden paths and secrets that will help you navigate its depths with greater ease.": "在你的新形态下，地精的记忆碎片会涌入你的脑海。这些对过去的一瞥让你对洞穴地下城有了宝贵的见解，揭示了隐藏的路径和秘密，将帮助你更轻松地导航到它的深处。",
    "SAFE PLACE": "安全地点",
    "You come across a safe room, a rare sanctuary amidst the challenges of the cave dungeon. The relentless journey has been wearing down your mental endurance, leaving you strained. Here, you can take a moment to rest and recover your sanity, regaining the strength needed to press onward.": "在洞穴地牢的挑战中，你发现了一间密室，这是一个罕见的避难所。无情的旅程已经消耗了你的精神耐力，让你紧张。在这里，你可以休息一会儿，恢复你的理智，重新获得继续前进所需的力量。",
    "Deep Thoughts": "深思",
    "Use Map": "使用地图",
    "Cunning Mind": "狡猾的头脑",
    "Fight Rat Army": "对抗老鼠大军",
    "RAT ARMY": "老鼠大军",
    "Rat Army": "老鼠大军",
    "You accidentally stumble into a passage teeming with rats. Drawn by the scent of blood, the swarm reacts instantly, surging toward you in a relentless wave. Overwhelmed and outnumbered, you must summon all your strength and wits to fight for your survival.": "你不小心跌进了一条满是老鼠的通道。被血的气味吸引，鼠群立即做出反应，无情地向你涌来。在寡不敌众的情况下，你必须鼓起所有的力量和智慧来为生存而战。",
    "Dagger Jab": "匕首刺击",
    "Look for Rats": "寻找老鼠",
    "RATS DISPERSED": "老鼠散去",
    "You’ve vanquished the swarm of rats, but their frail bodies hold no value for you to absorb. A handful of weaklings still scurry about the room, though they pose no threat. The passage ahead is now clear, allowing you to move forward. However, you could choose to linger a little longer, dispatching the remaining rats out of sheer spite.": "你已经击败了这群老鼠，但它们脆弱的身体对你来说毫无吸收价值。几个虚弱的家伙仍然在房间里跑来跑去，尽管他们没有构成威胁。前方的通道现在畅通了，你可以继续前进。然而，你也可以选择再多待一会儿，把剩下的老鼠赶出去。",
    "ESCAPED": "逃跑了",
    "Lose 2% XP": "失去 2% 经验值",
    "Rat": "老鼠",
    "You’ve managed to escape the battle, slipping away from danger and living to face another challenge.": "你成功地逃离了这场战斗，逃离了危险，活着面对另一个挑战。",
    "Fight Spectral Wolf": "对抗幽灵狼",
    "GHOSTLY WOLF": "幽灵狼",
    "You come face-to-face with a glowing spectral wolf, its movements graceful and otherworldly. With each step, a faint, shimmering sparkle trails from its paw prints, casting an ethereal glow across the room. As the creature prowls, its gaze locks onto you. Without warning, it lunges forward, teeth bared. There’s no escape—you must fight.": "你与一只发光的幽灵狼面对面，它的动作优雅而超凡脱俗。每走一步，它的爪印上就会留下微弱的闪光，在整个房间里投射出一种飘渺的光芒。当这个生物徘徊时，它的目光锁定在你身上。毫无征兆地，它向前扑去，露出牙齿。无处可逃——你必须战斗。",
    "Spectral Wolf": "幽灵狼",
    "TIME LIMIT": "时间限制",
    "You must overcome this special encounter within the given time limit. Fail to do so, and you will be overwhelmed, leaving you no choice but to retreat in defeat.": "你必须在规定的时间内克服这个特殊的遭遇。如果做不到这一点，你就会被压倒，只能在失败中撤退。",
    "AFTERMATH": "余波",
    "The defeated wolf disintegrates into shimmering particles of light, leaving no trace behind. You are taken aback by the presence of such magical beasts in this dungeon. Shaking off your surprise, you continue on your journey, deeper into the unknown.": "被击败的狼分解成闪烁的光粒子，不留痕迹。你会被地牢里出现的这些神奇的野兽吓一跳。摆脱你的惊讶，你继续你的旅程，深入未知。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "- Physical": "- 物理",
    "- Retreat from battle": "- 从战斗中撤退",
    "- Engage battle.": "- 参与战斗.",
    "- Use brute force.": "- 使用蛮力.",
    "- Solve the lock puzzle.": "- 解开锁的谜题.",
    "- Hides maxed options.": "- 隐藏已最大选项.",
    "- Auto buy sanity.": "- 自动购买理智.",
    "- Gain bat form.": "- 获得蝙蝠形态.",
    "- Gain wolf form.": "- 获得狼形态.",
    "- Gain goblin form.": "- 获得哥布林形态.",
    "- Remain in current form.": "- 保持当前形态.",
    "- Explore the cave, further takes longer time.": "- 探索洞穴，距离更远需要更长的时间.",
    "- Unlocks Sanity.": "- 解锁理智.",
    "- Unlock new Blood skills.": "- 解锁新的血液技能.",
    "- Unlock new Exploration skills.": "- 解锁新的探索技能.",
    "- Unlock new Sanity skills.": "- 解锁新的理智技能.",
    "- Unlocks new Sanity skills.": "- 解锁新的理智技能.",
    "- Discover new skills.": "- 发现新技能.",
    "- Unlocks Exploration.": "- 解锁探索.",
    "- Auto gain blood.": "- 自动获取血液.",
    "- Gain sanity.": "- 获得理智.",
    "- Gain awareness.": "- 获得意识.",
    "- Click to gain blood.": "- 点击以获取血液.",
    "uxwing.com": "uxwing.com",
    "pixabay.com": "pixabay.com",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "- Exploration time faster (-": "- 探索时间更快 (-",
    "- Exploration time longer (+": "- 探索时间更长 (+",
    "- Exploration progress (+": "- 探索进度 (+",
    "- Exploration speed (+": "- 探索速度 (+",
    "- Exploration gain (+": "- 探索获取 (+",
    "- Blood gain (+": "- 血液获取 (+",
    "- Blood speed (+": "- 血液速度 (+",
    "- Max blood (+": "- 血液上限 (+",
    "- Max sanity (+": "- 理智上限 (+",
    "- Sanity gain (+": "- 理智获取 (+",
    "- Sanity speed (+": "- 理智速度 (+",
    "Use: ": "使用: ",
    "Wolf: ": "狼: ",
    "Bat: ": "蝙蝠: ",
    "Goblin: ": "哥布林: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " MISS": " 未命中",
    " HIT": " 命中",
    " CRITICAL": " 暴击",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s\).$/,
    /^([\d\.]+)\).$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\% $/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Sanity$/, '$1 理智'],
    [/^([\d\.,]+) Blood$/, '$1 血液'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^You have gained ([\d\.,]+) XP.$/, '你获得了 $1 经验值.'],
    [/^\- Lv.([\d\.,]+) Lonely Rat \(([\d\.,]+) xp\)$/, '- 等级 $1 落单老鼠 ($2 经验值)'],
    [/^\- Lv.([\d\.,]+) Magical Wolf \(([\d\.,]+) xp\)$/, '- 等级 $1 魔法狼 ($2 经验值)'],
    [/^\- Lv.([\d\.,]+) Swarm of Rats \(([\d\.,]+) xp\)$/, '- 等级 $1 鼠群 ($2 经验值)'],
    [/^\- Lv.([\d\.,]+) Goblin Guard \(([\d\.,]+) xp\)$/, '- 等级 $1 哥布林守卫 ($2 经验值)'],
    [/^Lvl ([\d\.,]+) \-$/, '等级 $1 \-'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);